# Generated by Django 2.2.2 on 2019-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_auto_20190630_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
