# Generated by Django 2.2.2 on 2019-07-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0011_querysearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='image/'),
        ),
        migrations.CreateModel(
            name='Commentsblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post.Blogpost')),
            ],
        ),
    ]
